### ISSUE TITLE
conflict: jersey 1.x and jersey 2.x

### ISSUE THREAD

**Issue by gsmachado** [EMCECS/smart-client-java#1]
Hello,

I've seen that you guys are using Jersey 1.x, which is kind of incompatible to Jersey 2.x. I'm using an application which is implemented with Jersey 2.x (e.g., client), and I wonder if and how I can solve such conflict. Someone could enlighten me here?

Or you guys are planning to release a new version of the smart-client-java that is based on Jersey 2.x?

Cheers!

**Comment by twincitiesguy** [comment]
@gsmachado,

We actually started out with Jersey 2.x and unfortunately found that it lacks the flexibility that we need in our filters to accomplish load balancing.  Jersey 2.x does not offer a way to wrap the execution of a request the way 1.x filters do.  Therefore, we're stuck using 1.x.

I would analyze whether you actually need Jersey 2.x and if not, simply use 1.x instead.  If there is a specific feature in 2.x that you need, please let us know as it will probably affect other users.
